//
// Created by carlostojal on 01-05-2023.
//

#ifndef PCL_AGGREGATOR_CORE_RGBDDEPROJECTOR_H
#define PCL_AGGREGATOR_CORE_RGBDDEPROJECTOR_H

#include <eigen3/Eigen/Dense>
#include <pcl/point_cloud.h>
#include <pcl/point_types.h>
#include <opencv2/opencv.hpp>

namespace pcl_aggregator {
    namespace utils {

        class RGBDDeprojector {

            private:
                Eigen::Matrix3d K; // camera intrinsic matrix
                std::string camera_frame_id; // the frame id of the camera
                pcl::PointCloud<pcl::PointXYZRGBL> cloud; // the cloud generated by the deprojection
                cv::Mat last_depth_image;
                cv::Mat last_color_image;
        };

    } // pcl_aggregator
} // utils

#endif //PCL_AGGREGATOR_CORE_RGBDDEPROJECTOR_H
