//
// Created by carlostojal on 30-04-2023.
//

#ifndef PCL_AGGREGATOR_CORE_POINTCLOUDSMANAGER_H
#define PCL_AGGREGATOR_CORE_POINTCLOUDSMANAGER_H


class PointCloudsManager {

};


#endif //PCL_AGGREGATOR_CORE_POINTCLOUDSMANAGER_H
